name: Publish NPM package

on:
  release:
    types: [published]

jobs:
  alpha-publish:
    permissions:
      contents: write
      packages: write
      pull-requests: write
      id-token: write

    runs-on: ubuntu-latest
    env:
      CONFIG_TYPE: "UAT"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nodejs and npm
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@viplatform"
          cache: "yarn"

      - name: Setup yarn
        run: npm install -g yarn

      - name: Build prod install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build Prod Bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Stash uncommitted changes
        run: git stash --include-untracked

      - name: Publish package to npm
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
